//$file${.::meditation.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dpp.qm
// File:  ${.::meditation.c}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::meditation.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"               // QP/C real-time embedded framework
#include "dpp.h"               // DPP Application interface
#include "bsp.h"               // Board Support Package
#include <time.h>

//$declare${AOs::Meditation} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Meditation} .........................................................
typedef struct Meditation {
// protected:
    QActive super;

// private:
    QTimeEvt timeEvt;

// public:
} Meditation;

extern Meditation Meditation_inst;

// protected:
static QState Meditation_initial(Meditation * const me, void const * const par);
static QState Meditation_get_time(Meditation * const me, QEvt const * const e);
static QState Meditation_meditation_until_7(Meditation * const me, QEvt const * const e);
static QState Meditation_meditation_for_90_mins(Meditation * const me, QEvt const * const e);
static QState Meditation_state30m(Meditation * const me, QEvt const * const e);
static QState Meditation_state15m(Meditation * const me, QEvt const * const e);
static QState Meditation_state45m(Meditation * const me, QEvt const * const e);
static QState Meditation_state60m(Meditation * const me, QEvt const * const e);
static QState Meditation_state75m(Meditation * const me, QEvt const * const e);
static QState Meditation_state90m(Meditation * const me, QEvt const * const e);
//$enddecl${AOs::Meditation} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//----------------------------------------------------------------------------
Q_DEFINE_THIS_FILE

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::Meditation_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::Meditation_ctor} .................................................
void Meditation_ctor(void) {
    Meditation * const me = &Meditation_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&Meditation_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}
//$enddef${Shared::Meditation_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::AO_Meditation} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_Meditation} ...................................................
QActive * const AO_Meditation = &Meditation_inst.super;
//$enddef${Shared::AO_Meditation} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Meditation} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Meditation} .........................................................
Meditation Meditation_inst;

//${AOs::Meditation::SM} .....................................................
static QState Meditation_initial(Meditation * const me, void const * const par) {
    //${AOs::Meditation::SM::initial}
    Q_UNUSED_PAR(par);

    #ifdef Q_SPY
        Meditation * Meditation_inst = me;
        QS_OBJ_DICTIONARY(Meditation_inst);

        QTimeEvt * Meditation_timeEvt = &me->timeEvt;
        QS_OBJ_DICTIONARY(Meditation_timeEvt);
    #endif


    QS_FUN_DICTIONARY(&Meditation_get_time);
    QS_FUN_DICTIONARY(&Meditation_meditation_until_7);
    QS_FUN_DICTIONARY(&Meditation_meditation_for_90_mins);
    QS_FUN_DICTIONARY(&Meditation_state30m);
    QS_FUN_DICTIONARY(&Meditation_state15m);
    QS_FUN_DICTIONARY(&Meditation_state45m);
    QS_FUN_DICTIONARY(&Meditation_state60m);
    QS_FUN_DICTIONARY(&Meditation_state75m);
    QS_FUN_DICTIONARY(&Meditation_state90m);

    return Q_TRAN(&Meditation_get_time);
}

//${AOs::Meditation::SM::get_time} ...........................................
static QState Meditation_get_time(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time}
        case Q_ENTRY_SIG: {
            QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_SEC, BSP_TICKS_PER_SEC);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time}
        case Q_EXIT_SIG: {
            (void)QTimeEvt_disarm(&me->timeEvt);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::TIMEOUT}
        case TIMEOUT_SIG: {
            struct tm t = BSP_getTime();
            //${AOs::Meditation::SM::get_time::TIMEOUT::[between-5-am-and-7-am]}
            if ((t.tm_hour >= 5) && (t.tm_hour < 7)) {
                status_ = Q_TRAN(&Meditation_meditation_until_7);
            }
            //${AOs::Meditation::SM::get_time::TIMEOUT::[else]}
            else {
                status_ = Q_HANDLED();
            }
            break;
        }
        //${AOs::Meditation::SM::get_time::NEW_TIME}
        case NEW_TIME_SIG: {
            NewTimeEvt* evt = Q_EVT_CAST(NewTimeEvt);
            struct tm time;

            time.tm_hour = evt->hours;
            time.tm_min = evt->minutes;
            time.tm_sec = evt->seconds;

            BSP_setTime(time);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::START_MEDITATION}
        case START_MEDITATION_SIG: {
            status_ = Q_TRAN(&Meditation_meditation_for_90_mins);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_until_7} .......................
static QState Meditation_meditation_until_7(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_until_7}
        case Q_ENTRY_SIG: {
            BSP_ledOn();
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_until_7}
        case Q_EXIT_SIG: {
            BSP_ledOff();
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_until~::TIMEOUT}
        case TIMEOUT_SIG: {
            struct tm t = BSP_getTime();
            //${AOs::Meditation::SM::get_time::meditation_until~::TIMEOUT::[after-7-am]}
            if ((t.tm_hour < 5) || (t.tm_hour >= 7)) {
                status_ = Q_TRAN(&Meditation_get_time);
            }
            //${AOs::Meditation::SM::get_time::meditation_until~::TIMEOUT::[15/30/45-mins]}
            else if (// is seconds is 0 or 1 on every 15 mins
                     (t.tm_sec <= 1) &&
                         ((t.tm_min == 15) || (t.tm_min == 30) || (t.tm_min == 45)))
            {
                BSP_playAudio();
                status_ = Q_HANDLED();
            }
            //${AOs::Meditation::SM::get_time::meditation_until~::TIMEOUT::[else]}
            else {
                status_ = Q_HANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_get_time);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_90_mins} ...................
static QState Meditation_meditation_for_90_mins(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_90_mins}
        case Q_ENTRY_SIG: {
            BSP_ledOn();
            BSP_playAudio();
            (void)QTimeEvt_disarm(&me->timeEvt);
            QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_SEC * 60 * 15, BSP_TICKS_PER_SEC * 60 * 15);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_90_mins}
        case Q_EXIT_SIG: {
            BSP_ledOff();
            QTimeEvt_rearm(&me->timeEvt, BSP_TICKS_PER_SEC);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Meditation_state15m);
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_get_time);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_9~::state30m} ..............
static QState Meditation_state30m(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state30m}
        case Q_ENTRY_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state30m::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Meditation_state45m);
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_meditation_for_90_mins);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_9~::state15m} ..............
static QState Meditation_state15m(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state15m}
        case Q_ENTRY_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state15m::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Meditation_state30m);
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_meditation_for_90_mins);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_9~::state45m} ..............
static QState Meditation_state45m(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state45m}
        case Q_ENTRY_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state45m::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Meditation_state60m);
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_meditation_for_90_mins);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_9~::state60m} ..............
static QState Meditation_state60m(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state60m}
        case Q_ENTRY_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state60m::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Meditation_state75m);
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_meditation_for_90_mins);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_9~::state75m} ..............
static QState Meditation_state75m(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state75m}
        case Q_ENTRY_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state75m::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Meditation_state90m);
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_meditation_for_90_mins);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_9~::state90m} ..............
static QState Meditation_state90m(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state90m}
        case Q_ENTRY_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state90m}
        case Q_EXIT_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state90m::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Meditation_get_time);
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_meditation_for_90_mins);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Meditation} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
