//$file${.::meditation.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dpp.qm
// File:  ${.::meditation.c}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::meditation.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"               // QP/C real-time embedded framework
#include "dpp.h"               // DPP Application interface
#include "bsp.h"               // Board Support Package
#include <time.h>

//$declare${AOs::Meditation} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Meditation} .........................................................
typedef struct Meditation {
// protected:
    QActive super;

// private:
    QTimeEvt timeEvt;

// public:

// protected:
    struct tm alarm;
} Meditation;

extern Meditation Meditation_inst;

// protected:
static void Meditation_alarm_goes_off_in(Meditation * const me,
    uint32_t seconds_in_future);

// protected:
static QState Meditation_initial(Meditation * const me, void const * const par);
static QState Meditation_get_time(Meditation * const me, QEvt const * const e);
static QState Meditation_meditation_until_7(Meditation * const me, QEvt const * const e);
static QState Meditation_meditation_for_90_mins(Meditation * const me, QEvt const * const e);
static QState Meditation_state30m(Meditation * const me, QEvt const * const e);
static QState Meditation_state45m(Meditation * const me, QEvt const * const e);
static QState Meditation_state60m(Meditation * const me, QEvt const * const e);
static QState Meditation_state75m(Meditation * const me, QEvt const * const e);
static QState Meditation_state90m(Meditation * const me, QEvt const * const e);
//$enddecl${AOs::Meditation} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//----------------------------------------------------------------------------
Q_DEFINE_THIS_FILE

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::Meditation_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::Meditation_ctor} .................................................
void Meditation_ctor(void) {
    Meditation * const me = &Meditation_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&Meditation_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}
//$enddef${Shared::Meditation_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::AO_Meditation} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_Meditation} ...................................................
QActive * const AO_Meditation = &Meditation_inst.super;
//$enddef${Shared::AO_Meditation} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Meditation} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Meditation} .........................................................
Meditation Meditation_inst;

//${AOs::Meditation::alarm_goes_off_in} ......................................
static void Meditation_alarm_goes_off_in(Meditation * const me,
    uint32_t seconds_in_future)
{
    struct tm t = BSP_getTime();

    time_t secs = (t.tm_hour * 60 * 60) + (t.tm_min * 60) + t.tm_sec;

    secs += seconds_in_future;;

    me->alarm = *localtime(&secs);    // save it

    QS_BEGIN_ID(100, 0U)
            QS_STR(__func__);     // String function
            QS_U8(1, me->alarm.tm_hour);         // Hours
            QS_U8(1, me->alarm.tm_min);         // Minutes
            QS_U8(1, me->alarm.tm_sec);  // Seconds
    QS_END()
}

//${AOs::Meditation::SM} .....................................................
static QState Meditation_initial(Meditation * const me, void const * const par) {
    //${AOs::Meditation::SM::initial}
    Q_UNUSED_PAR(par);

    #ifdef Q_SPY
        Meditation * Meditation_inst = me;
        QS_OBJ_DICTIONARY(Meditation_inst);

        QTimeEvt * Meditation_timeEvt = &me->timeEvt;
        QS_OBJ_DICTIONARY(Meditation_timeEvt);
    #endif


    QS_FUN_DICTIONARY(&Meditation_get_time);
    QS_FUN_DICTIONARY(&Meditation_meditation_until_7);
    QS_FUN_DICTIONARY(&Meditation_meditation_for_90_mins);
    QS_FUN_DICTIONARY(&Meditation_state30m);
    QS_FUN_DICTIONARY(&Meditation_state45m);
    QS_FUN_DICTIONARY(&Meditation_state60m);
    QS_FUN_DICTIONARY(&Meditation_state75m);
    QS_FUN_DICTIONARY(&Meditation_state90m);

    return Q_TRAN(&Meditation_get_time);
}

//${AOs::Meditation::SM::get_time} ...........................................
static QState Meditation_get_time(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time}
        case Q_ENTRY_SIG: {
            QTimeEvt_armX(&me->timeEvt, BSP_TICKS_PER_SEC, BSP_TICKS_PER_SEC);
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time}
        case Q_EXIT_SIG: {
            (void)QTimeEvt_disarm(&me->timeEvt);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::TIMEOUT}
        case TIMEOUT_SIG: {
            struct tm t = BSP_getTime();

            if ((t.tm_hour >= 5) && (t.tm_hour < 7))
            {
                // morning meditation start
                static QEvt const evt1 = QEVT_INITIALIZER(MORNING_MEDITATION_START_SIG);
                QACTIVE_POST(&me->super, &evt1, me);
            }

            if ((t.tm_sec <= 1) &&
                ((t.tm_min == 15) || (t.tm_min == 30) || (t.tm_min == 45)))
            {
                // minute_quarter
                static QEvt const evt3 = QEVT_INITIALIZER(MINUTE_QUARTER_SIG);
                QACTIVE_POST(&me->super, &evt3, me);
            }

            if ((t.tm_sec <= 1) && (t.tm_min == 0))
            {
                // on the hour
                static QEvt const evt4 = QEVT_INITIALIZER(ON_THE_HOUR_SIG);
                QACTIVE_POST(&me->super, &evt4, me);
            }

            if ((t.tm_hour < 5) || (t.tm_hour >= 7))
            {
                // morning meditation end
                static QEvt const evt2 = QEVT_INITIALIZER(MORNING_MEDITATION_END_SIG);
                QACTIVE_POST(&me->super, &evt2, me);
            }

            if (
                (t.tm_sec == me->alarm.tm_sec) &&
                (t.tm_min == me->alarm.tm_min) &&
                (t.tm_hour == me->alarm.tm_hour)
                )
            {
                // alarm
                static QEvt const evt5 = QEVT_INITIALIZER(ALARM_SIG);
                QACTIVE_POST(&me->super, &evt5, me);
            }

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::NEW_TIME}
        case NEW_TIME_SIG: {
            const NewTimeEvt* evt = Q_EVT_CAST(NewTimeEvt);
            struct tm time;

            time.tm_hour = evt->hours;
            time.tm_min = evt->minutes;
            time.tm_sec = evt->seconds;

            BSP_setTime(time);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::START_MEDITATION}
        case START_MEDITATION_SIG: {
            status_ = Q_TRAN(&Meditation_meditation_for_90_mins);
            break;
        }
        //${AOs::Meditation::SM::get_time::MORNING_MEDITATION_START}
        case MORNING_MEDITATION_START_SIG: {
            status_ = Q_TRAN(&Meditation_meditation_until_7);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_until_7} .......................
static QState Meditation_meditation_until_7(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_until_7}
        case Q_ENTRY_SIG: {
            BSP_ledOn();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_until_7}
        case Q_EXIT_SIG: {
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_until~::MORNING_MEDITATION_END}
        case MORNING_MEDITATION_END_SIG: {
            status_ = Q_TRAN(&Meditation_get_time);
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_until~::MINUTE_QUARTER}
        case MINUTE_QUARTER_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_until~::ON_THE_HOUR}
        case ON_THE_HOUR_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_until~::MORNING_MEDITATION_START}
        case MORNING_MEDITATION_START_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_get_time);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_90_mins} ...................
static QState Meditation_meditation_for_90_mins(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_90_mins}
        case Q_ENTRY_SIG: {
            BSP_ledOn();
            BSP_playAudio();

            Meditation_alarm_goes_off_in(me, 15*60);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_90_mins}
        case Q_EXIT_SIG: {
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::ALARM}
        case ALARM_SIG: {
            Meditation_alarm_goes_off_in(me, 15*60);
            status_ = Q_TRAN(&Meditation_state30m);
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::MORNING_MEDITATION_START}
        case MORNING_MEDITATION_START_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_get_time);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_9~::state30m} ..............
static QState Meditation_state30m(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state30m}
        case Q_ENTRY_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state30m::ALARM}
        case ALARM_SIG: {
            Meditation_alarm_goes_off_in(me, 15*60);
            status_ = Q_TRAN(&Meditation_state45m);
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_meditation_for_90_mins);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_9~::state45m} ..............
static QState Meditation_state45m(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state45m}
        case Q_ENTRY_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state45m::ALARM}
        case ALARM_SIG: {
            Meditation_alarm_goes_off_in(me, 15*60);
            status_ = Q_TRAN(&Meditation_state60m);
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_meditation_for_90_mins);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_9~::state60m} ..............
static QState Meditation_state60m(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state60m}
        case Q_ENTRY_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state60m::ALARM}
        case ALARM_SIG: {
            Meditation_alarm_goes_off_in(me, 15*60);
            status_ = Q_TRAN(&Meditation_state75m);
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_meditation_for_90_mins);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_9~::state75m} ..............
static QState Meditation_state75m(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state75m}
        case Q_ENTRY_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state75m::ALARM}
        case ALARM_SIG: {
            Meditation_alarm_goes_off_in(me, 15*60);
            status_ = Q_TRAN(&Meditation_state90m);
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_meditation_for_90_mins);
            break;
        }
    }
    return status_;
}

//${AOs::Meditation::SM::get_time::meditation_for_9~::state90m} ..............
static QState Meditation_state90m(Meditation * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state90m}
        case Q_ENTRY_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state90m}
        case Q_EXIT_SIG: {
            BSP_playAudio();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Meditation::SM::get_time::meditation_for_9~::state90m::ALARM}
        case ALARM_SIG: {
            status_ = Q_TRAN(&Meditation_get_time);
            break;
        }
        default: {
            status_ = Q_SUPER(&Meditation_meditation_for_90_mins);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Meditation} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
